SudokuGrid
int SudokuGrid.columns
Referenced by SetSquarePosition, spawnGridSquares.
int SudokuGrid.rows
Referenced by spawnGridSquares.
float SudokuGrid.square_offset
Referenced by SetSquarePosition.
GameObject SudokuGrid.grid_square
Referenced by spawnGridSquares, Start.
Vector2 SudokuGrid.start_position
Referenced by SetSquarePosition.
float SudokuGrid.square_scale
Referenced by spawnGridSquares.
float SudokuGrid.square_gap
Referenced by SetSquarePosition.
Color SudokuGrid.line_highlight_color
Referenced by OnSquareSelected.
List<GameObject> SudokuGrid.grid_squares_
Referenced by CheckBoardCompleted, OnDisable, SetGridNotes, setGridSquareData, SetSquarePosition, SetSquaresColor, SolveSudoku, spawnGridSquares.
int SudokuGrid.selected_grid_data
Referenced by OnDisable, SetGridFormFile, SetGridNumber.
void SudokuGrid.Start()
References CreateGrid, GameSettings.GetContinuePreviousGame, GameSettings.GetGameMode, grid_square, GameSettings.Instance, SetGridFormFile, SetGridNumber.
void SudokuGrid.SetGridFormFile()
References Config.GetGridNotes, selected_grid_data, SetGridNotes, setGridSquareData.
Referenced by Start.
void SudokuGrid.SetGridNotes(Dictionary< int, List< int >> notes)
References grid_squares_.
Referenced by SetGridFormFile.
void SudokuGrid.Update()
void SudokuGrid.CreateGrid()
References SetSquarePosition, spawnGridSquares.
Referenced by Start.
void SudokuGrid.spawnGridSquares()
References columns, grid_square, grid_squares_, rows, square_scale.
Referenced by CreateGrid.
void SudokuGrid.SetSquarePosition()
References columns, grid_squares_, square_gap, square_offset, start_position.
Referenced by CreateGrid.
void SudokuGrid.SetGridNumber(string level)
References selected_grid_data, setGridSquareData.
Referenced by Start.
void SudokuGrid.setGridSquareData(SudokuData.SudokuBoardData data)
References grid_squares_.
Referenced by SetGridFormFile, SetGridNumber.
void SudokuGrid.OnEnable()
References CheckBoardCompleted, OnSquareSelected.
void SudokuGrid.OnDisable()
References CheckBoardCompleted, Lives.GetErrorNumber, GameSettings.GetExitAfterWon, grid_squares_, Lives.instance, GameSettings.Instance, OnSquareSelected, selected_grid_data.
void SudokuGrid.SetSquaresColor(int[] data, Color col)
References grid_squares_.
Referenced by OnSquareSelected.
void SudokuGrid.CheckBoardCompleted()
References grid_squares_.
Referenced by OnDisable, OnEnable, SolveSudoku.
void SudokuGrid.OnSquareSelected(int square_index)
References LineIndicator.GetAllSquareIndexes, LineIndicator.instance, line_highlight_color, SetSquaresColor.
Referenced by OnDisable, OnEnable.
void SudokuGrid.SolveSudoku()
References CheckBoardCompleted, grid_squares_.