Clock
int Clock.hour_
int Clock.minute_
int Clock.seconds_
Text Clock.textClock
Referenced by Awake, GetCurrentTimeText.
float Clock.delta_time
Referenced by Awake, Update.
bool Clock.stop_clock_
Referenced by OnGameOver, Start, Update.
Clock Clock.instance
Referenced by Awake.
void Clock.Awake()
References delta_time, GameSettings.GetContinuePreviousGame, GameSettings.Instance, instance, Config.ReadGameTime, textClock.
void Clock.Start()
References stop_clock_.
void Clock.Update()
References delta_time, GameSettings.GetPaused, GameSettings.Instance, LeadingZero, stop_clock_.
string Clock.LeadingZero(int n)
Referenced by Update.
void Clock.OnEnable()
References OnGameOver.
void Clock.OnDisable()
References OnGameOver.
void Clock.OnGameOver()
References stop_clock_.
Referenced by OnDisable, OnEnable.
Text Clock.GetCurrentTimeText()
References textClock.
static string Clock.GetCurrentTime()