PauseHandler
bool PauseHandler.isPaused
Referenced by Paused, UnPaused, Update.
GameObject PauseHandler.pauseMenu
GameObject PauseHandler.optionsMenu
Referenced by Update.
void PauseHandler.Paused()
References isPaused.
Referenced by Update.
void PauseHandler.Start()
References UnPaused.
void PauseHandler.Update()
References isPaused, optionsMenu, Paused, UnPaused.
void PauseHandler.UnPaused()
References isPaused.
Referenced by Start, Update.