GameSettings
EGameMode
GameSettings GameSettings.Instance
Referenced by Awake, Clock.Awake, SudokuGrid.OnDisable, SudokuGrid.Start, Lives.Start, GridSquare.Start, Clock.Update.
EGameMode GameSettings._GameMode
Referenced by GetGameMode, SetGameMode, Start.
bool GameSettings._continuePreviousGame
Referenced by GetContinuePreviousGame, SetContinuePreviousGame, SetExitAfterWon, Start.
bool GameSettings._exitAfterWon
Referenced by GetExitAfterWon, SetExitAfterWon.
bool GameSettings._Paused
Referenced by Awake, GetPaused, SetPaused.
void GameSettings.Awake()
References _Paused, Instance.
void GameSettings.Start()
References _continuePreviousGame, _GameMode.
void GameSettings.SetExitAfterWon(bool set)
References _continuePreviousGame, _exitAfterWon.
bool GameSettings.GetExitAfterWon()
References _exitAfterWon.
Referenced by SudokuGrid.OnDisable.
void GameSettings.SetContinuePreviousGame(bool continue_game)
References _continuePreviousGame.
bool GameSettings.GetContinuePreviousGame()
References _continuePreviousGame.
Referenced by Clock.Awake, SudokuGrid.Start, Lives.Start, GridSquare.Start.
void GameSettings.SetPaused(bool paused)
References _Paused.
bool GameSettings.GetPaused()
References _Paused.
Referenced by Clock.Update.
void GameSettings.SetGameMode(EGameMode mode)
References _GameMode.
Referenced by SetGameMode.
void GameSettings.SetGameMode(string mode)
References SetGameMode.
string GameSettings.GetGameMode()
References _GameMode.
Referenced by SudokuGrid.Start.