Config
string Config.dir
string Config.file
Referenced by ErrorNumber, GetGridNotes, ReadBoardLevel, ReadGameBoardLevel, ReadGameTime, ReadGridData.
string Config.path
Referenced by DeleteDataFile, ErrorNumber, GameDataFileExist, GetGridNotes, ReadBoardLevel, ReadGameBoardLevel, ReadGameTime, ReadGridData, SaveBoardData.
static void Config.DeleteDataFile()
References path.
static void Config.SaveBoardData(SudokuData.SudokuBoardData board_data, string level, int board_index, int error_number, Dictionary< string, List< string >> grid_notes)
References path.
static Dictionary<int, List<int> > Config.GetGridNotes()
References file, path.
Referenced by SudokuGrid.SetGridFormFile.
static string Config.ReadBoardLevel()
References file, path.
static SudokuData.SudokuBoardData Config.ReadGridData()
References file, path.
static int Config.ReadGameBoardLevel()
References file, path.
static float Config.ReadGameTime()
References file, path.
Referenced by Clock.Awake.
static int Config.ErrorNumber()
References file, path.
static bool Config.GameDataFileExist()
References path.
Referenced by ContinueButton.Start.