LineIndicator
LineIndicator LineIndicator.instance
Referenced by Awake, SudokuGrid.OnSquareSelected.
int [,] LineIndicator.line_data
Referenced by GetHorizontalLine, GetSquare, GetVerticalLine.
int [] LineIndicator.line_data_falt
Referenced by GetAllSquareIndexes.
int [,] LineIndicator.square_data
Referenced by GetSquare.
LineIndicator.int
void LineIndicator.Awake()
References instance.
int LineIndicator.GetSquarePosition(int square_index)
Referenced by GetHorizontalLine, GetVerticalLine.
int [] LineIndicator.GetHorizontalLine(int square_index)
References GetSquarePosition, line_data.
int [] LineIndicator.GetVerticalLine(int square_index)
References GetSquarePosition, line_data.
int [] LineIndicator.GetSquare(int square_index)
References line_data, square_data.
int [] LineIndicator.GetAllSquareIndexes()
References line_data_falt.
Referenced by SudokuGrid.OnSquareSelected.