Lives
List<GameObject> Lives.error_images
Referenced by Start, WrongNumber.
GameObject Lives.game_over_popup
int Lives.lives_
Referenced by CheckForGameOver, Start, WrongNumber.
int Lives.error_number_
Referenced by GetErrorNumber, Start, WrongNumber.
Lives Lives.instance
Referenced by Awake, SudokuGrid.OnDisable.
void Lives.Awake()
References instance.
void Lives.Start()
References error_images, error_number_, GameSettings.GetContinuePreviousGame, GameSettings.Instance, lives_.
void Lives.WrongNumber()
References CheckForGameOver, error_images, error_number_, lives_.
Referenced by OnDisable, OnEnable.
void Lives.CheckForGameOver()
References lives_.
Referenced by WrongNumber.
void Lives.OnEnable()
References WrongNumber.
void Lives.OnDisable()
References WrongNumber.
int Lives.GetErrorNumber()
References error_number_.
Referenced by SudokuGrid.OnDisable.