GridSquare
GameObject GridSquare.number_text
List<GameObject> GridSquare.number_notes
Referenced by GetSquareNotes, SetClearEmptyNotes, SetNoteNumberValue, SetNoteSingleNumberValue.
bool GridSquare.note_active
Referenced by OnNotesActive, OnSetNumber, SetNoteSingleNumberValue, Start.
int GridSquare.number_
Referenced by DisplayText, GetSquareNumber, IsCorrectNumberSet, OnClearNumber, OnSetNumber, SetCorrectNumber, SetNumber.
int GridSquare.correct_number_
Referenced by IsCorrectNumberSet, OnSetNumber, SetCorrectNumber.
bool GridSquare.selected_
Referenced by IsSelected, OnClearNumber, OnPointerClick, OnSetNumber, OnSquareSelected, Start.
int GridSquare.square_index_
Referenced by OnPointerClick, OnSquareSelected, SetSquareIndex.
bool GridSquare.has_default_value_
Referenced by GetHasDefaultValue, OnClearNumber, OnSetNumber, SetHasDefaultValue.
bool GridSquare.has_wrong_value_
Referenced by HasWrongValue, OnClearNumber, OnSetNumber, SetCorrectNumber.
int GridSquare.GetSquareNumber()
References number_.
bool GridSquare.IsCorrectNumberSet()
References correct_number_, number_.
bool GridSquare.HasWrongValue()
References has_wrong_value_.
void GridSquare.SetHasDefaultValue(bool has_default)
References has_default_value_.
bool GridSquare.GetHasDefaultValue()
References has_default_value_.
bool GridSquare.IsSelected()
References selected_.
void GridSquare.SetSquareIndex(int index)
References square_index_.
void GridSquare.SetCorrectNumber(int number)
References correct_number_, has_wrong_value_, number_, SetSquareColour.
void GridSquare.SetCorrectNumber()
References correct_number_, DisplayText, number_, SetNoteNumberValue.
List<string> GridSquare.GetSquareNotes()
References number_notes.
void GridSquare.SetGridNotes(List< int > notes)
References SetNoteSingleNumberValue.
void GridSquare.OnNotesActive(bool active)
References note_active.
Referenced by OnDisable, OnEnable.
void GridSquare.DisplayText()
References number_.
Referenced by OnClearNumber, SetCorrectNumber, SetNumber.
void GridSquare.SetNumber(int number)
References DisplayText, number_.
Referenced by OnSetNumber.
void GridSquare.OnPointerClick(PointerEventData eventData)
References selected_, square_index_.
void GridSquare.OnSubmit(BaseEventData eventData)
void GridSquare.OnEnable()
References OnClearNumber, OnNotesActive, OnSetNumber, OnSquareSelected.
void GridSquare.OnDisable()
References OnClearNumber, OnNotesActive, OnSetNumber, OnSquareSelected.
void GridSquare.OnClearNumber()
References DisplayText, has_default_value_, has_wrong_value_, number_, selected_, SetNoteNumberValue, SetSquareColour.
Referenced by OnDisable, OnEnable.
void GridSquare.OnSetNumber(int number)
References correct_number_, has_default_value_, has_wrong_value_, note_active, number_, selected_, SetNoteNumberValue, SetNoteSingleNumberValue, SetNumber.
Referenced by OnDisable, OnEnable.
void GridSquare.OnSquareSelected(int square_index)
References selected_, square_index_.
Referenced by OnDisable, OnEnable.
void GridSquare.SetSquareColour(Color col)
Referenced by OnClearNumber, SetCorrectNumber.
void GridSquare.Start()
References GameSettings.GetContinuePreviousGame, GameSettings.Instance, note_active, selected_, SetClearEmptyNotes, SetNoteNumberValue.
void GridSquare.SetClearEmptyNotes()
References number_notes.
Referenced by Start.
void GridSquare.SetNoteNumberValue(int value)
References number_notes.
Referenced by OnClearNumber, OnSetNumber, SetCorrectNumber, Start.
void GridSquare.SetNoteSingleNumberValue(int value, bool force_update=false)
References note_active, number_notes.
Referenced by OnSetNumber, SetGridNotes.